/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "1.9.22"
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    api(libs.com.google.code.findbugs.jsr305)
    api(libs.com.drewnoakes.metadata.extractor)
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.google.code.gson.gson)
    api(libs.org.apache.commons.commons.compress)
    api(libs.commons.io.commons.io)
    api(libs.javax.xml.bind.jaxb.api)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.hamcrest.hamcrest.all)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.com.jayway.awaitility.awaitility)
    testImplementation(libs.org.slf4j.slf4j.log4j12)
}

group = "de.maci.photography"
version = "1.1.1-SNAPSHOT"
description = "eyebeam-lib"
